### ISSUE TITLE
Line of sight casting

### ISSUE THREAD

**Issue by a-man-of-culture** [chromiecraft/chromiecraft#16]
##### SMALL DESCRIPTION:

In certain places (like the cave in the Valley of Trials) you can cast targeted spells without the line of sight.
https://vimeo.com/501255732

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Targeted spells on targets without a line of sight should be denied with the corresponding error message shown.

##### CURRENT BEHAVIOUR:

In some places you can cast targeted spells without the line of sight to their target.
The casts go off, their mana cost is spent.
The spells don't land, the targets are unaffected.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Get a caster to the cave in the Valley of Trials.
2.  Stand with some uneven ground or a corner of the cave wall between you and a monster.
3. Cast targeted spells.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Yehonal** [comment]
![image](https://user-images.githubusercontent.com/147092/104861878-cba83480-5931-11eb-9169-3ab5af964d4c.png)

The issue is here. https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L7532 We're investigating for a solution.

**Comment by Yehonal** [comment]
Should be fixed here: https://github.com/azerothcore/azerothcore-wotlk/pull/4308

Waiting for tests by AC contributors. I hope it will be merged on ChromieCraft soon

**Comment by Sathrenor** [comment]
_(Replying here to not make a duplicate)_

Unfortunately the issue is still in game and I would like to ask for a re-examination.
(Encountered: Teldrassil>Shadowglen>Shadowthread Cave). Video as a proof:
https://www.youtube.com/watch?v=wshUR8yYYYk&feature=youtu.be

**Comment by illfated** [comment]
Somewhat interesting issue, but mixed in with a lot of LoS events which I am fairly certain are normal and to be expected. Among others, the LoS issue occurs when there is enough terrain between player and the target mob, but I also don't know the exact details of the LoS height difference limits (Vmap / Z coordinates).

In my opinion, the only weird issue in your video seems to be that you were able to fire off the Wrath spell and not hit the targeted spider. I would have expected to see the "**Miss**" combat text for each of those casts, but did not manage to see any. Did you check your combat log to see if you got any spell miss entries in that situation?

**Comment by Sathrenor** [comment]
@illfated 
The "**Miss**" part was not meant to be a part of the video and yes, I had combat text disabled for the time of recording.

The problem is still a spell going off without any effect, but still consuming mana. It has been labelled as **Fixed**, but the issue still exists in live.

_(And personally, it is the first time I have encountered such bug despite playing on many more or less broken privs, and so I do not think it can be considered "normal and to be expected", sir.)_

**Comment by illfated** [comment]
Try opening a new ticket. Fill in the template with all the required information to make sure the ticket will be handled correctly.

**Comment by FrancescoBorzi** [comment]
FYI @Yehonal this issue has been reopened

**Comment by FrancescoBorzi** [comment]
FYI @Yehonal this issue has been reopened

**Comment by BrodieSinn** [comment]
LOS casting issue in Shadowglen cave in the Night Elf starting area with the spiders. Can cast on them and use mana but does not aggro or damage them.

**Comment by illfated** [comment]
Looks like the issue could be that the game client does not report "Miss" for some spell casts not hitting the target, mixed with potential incorrect LoS handling.

**Comment by KaelangWoW** [comment]
https://www.youtube.com/watch?v=PuDSslU1ph4 Would also like to add additional information to this ticket. See video.

**Comment by Stifler82** [comment]
> https://www.youtube.com/watch?v=PuDSslU1ph4 Would also like to add additional information to this ticket. See video.

beyond the bug in question, it is right for the spell to fail if it is faced with a LOS event.

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by Stifler82** [comment]
The problem has not been solved yet

**Video Test:** [Line of Sight](https://youtu.be/sq5tPhLb3c4)

**Comment by Stifler82** [comment]
@UltraNix
Fixed!
**Video Test:** [Line of sight casting, now works](https://youtu.be/fTDTsNl9ZRA)

**Comment by JamesHoffer** [comment]
@UltraNix
Fixed!
Video Test: Line of sight casting, now works

I just started playing on Chromie, and I have made several 10+ level characters, the LOS does not work properly anywhere against casters or throwers. Only melee NPC's.

**Comment by FrancescoBorzi** [comment]
@JamesHoffer 

> the LOS does not work properly anywhere

can you please open new issues with more details and examples? so we can reproduce the specific issues and fix them

cc @Yehonal @UltraNix

**Comment by UltraNix** [comment]
@JamesHoffer Pics or didn't happen :)
