### ISSUE TITLE
General Drakkisath sometimes resets when pulled to far away

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#2329]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

General Drakkisaths boss fight sometimes resets when pulled to far away from his original position (e.g. in Rends room)

### Expected Blizzlike Behaviour

Fight shouldnt reset.

### Steps to reproduce the problem

Kite Drakkisath

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
This is Vmaps/Mmaps/Pathfinding issue. While General is casting his spells players can run to some places or create situation what will disoriented boss. Way to solve issue right now: wait while boss is casting.
![WoWScrnShot_111521_012054](https://user-images.githubusercontent.com/85256266/141702689-8f51852b-914c-47ae-abf6-e567f08bd1d8.jpg)
.

**Comment by Shineslippers** [comment]
@j-hdt is it still issue? Look like now i can't repeat it

**Comment by j-hdt** [comment]
Was fixed last weekend - but on Wednesday a lot of regressions have been introduced and I did not have the chance to re-confirm it yet.

**Comment by Nyeriah** [comment]
> Was fixed last weekend - but on Wednesday a lot of regressions have been introduced and I did not have the chance to re-confirm it yet.

This is not possible - because there was no udpate last week, it was aborted due to instability issues. So it's still broken, absolutelly nothing was applied that could have addressed this issue by the way.

**Comment by j-hdt** [comment]
> > Was fixed last weekend - but on Wednesday a lot of regressions have been introduced and I did not have the chance to re-confirm it yet.
> 
> Hey,
> 
> This is not possible, because there was no update last week, it was aborted due to instability issues. So it's still broken, and absolutelly nothing was applied that could have addressed this issue by the way, so we don't have any regression here. My understanding of this issue is that it requires mmaps to be fixed.

Not talking about last week but about two days ago.
Wednesday, patches where applied and live - also causing some crashes. I even got to do some things that were fixed. Day afterwards, login message shows 18th of November again (instead of 23rd or 24th of November). Moreover, plenty of bugs appearing and re-appearing, hence it seems there where some regressions.
