### ISSUE TITLE
Execute sometimes does no Damage

### ISSUE THREAD

**Issue by Notrox1** [chromiecraft/chromiecraft#235]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

A week ago someone opened a ticket for execute but did not have enough information. I was recording while farming but most times this happens - it is hard to see because if Execute does no damage - the next autohit will kill the mob and its hard to see.
Today i had several times the problem that Execute does not do anything even after using it 2-3 times. 
Here is one video where you can see it very good
https://youtu.be/b3iOR69rcHA
So the Satyr drops under 20% and i keep pressing execute but nothing happens. This happens very often and even in BG - where maybe you hope to kill someone before he gets a heal of or out of range.

If I can any provide any further details here - please let me know

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Execute is meant a being a finisher so it should do damage to kill the target fast after reaching 20%
I am not sure if this is also happening in Blizzlike but definitly should not happen that often.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find a Mob preferably with higher HP Pool
2. Bring it to 20% and use Execute
3. If Execute does damage - repeat the steps
    If Execute does no damage - there is the issue

Maybe you can create a dummy with <20% hp to test this

##### EXTRA NOTES:

https://youtu.be/b3iOR69rcHA

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
It seems that the "Execute" spell fails, thanks for your report.

P.S.
This report is explained and illustrated so well that I would like to frame it like a bachelor's degree and hang it on the wall but I'd have sex with it first!

If all the reports were detailed and illustrated as well as yours, but above all true bug reports (since many of the reports are Client Bugs or issues that are not issues) we would have half of the current reports, given that in any case the greatest difficulty lies in the fact that many users do not explain the problem well or make incomplete reports.

**Comment by Notrox1** [comment]
Thanks - i am glad to hear I was able to provide the right informations :)

Thanks also for your support!

**Comment by Stifler82** [comment]
@Notrox1 
What Client WoW are you using? enUS or enGB?

**Comment by Stifler82** [comment]
**Video Test:** [Execute](https://youtu.be/w5IZUkqMxnw)

So, I did my tests..
and this is what I believe happened:
You were at level 29, and you went to engage in combat against a level 33 MOB (4 levels above you).
More higher a MOB is, and more are the chances of missing a hit.

So if you agree with my conclusions, I would say this is not a Bug and close the report, what do you think?

**Comment by Notrox1** [comment]
Hi @Stifler82 
I am using EnUS
Technically i think you are right - but this happens against every kind of mob and even in BG's. If it is a miss - it should dispay as one right? 
If this occurs - I am not even able to see that I used execute in the combat log. And this does not happen for any other spell.
I am not online very much atm but i could try to get a capture of a bg next week if that would help

**Comment by Stifler82** [comment]
> Hi @Stifler82
> I am using EnUS
> Technically i think you are right - but this happens against every kind of mob and even in BG's. If it is a miss - it should dispay as one right?
> If this occurs - I am not even able to see that I used execute in the combat log. And this does not happen for any other spell.
> I am not online very much atm but i could try to get a capture of a bg next week if that would help

to see what "Happens to you" and what "Happens to MOBS / Players" you hit, you also need to "Set" the Combat Log in the right way.

However, you have to keep in mind that the execute (it is not infallible), this means that you can miss the target even if the target is of the same level as you. Sure, obviously it will be a mostly "Rare" event, but that doesn't mean it can't happen at all.
This depends on the stats of the opponent, whether it is a MOB or a Player.

**Comment by Notrox1** [comment]
I will set up combat log correctly and try to reproduce it tomorrow. 
thanks for your support :)

**Comment by Notrox1** [comment]
Hi, sorry it took a bit longer
So i was farming for an hour over the last two days and kept a few examples.
Please excuse me for the watermark .. this are my first steps with video editing and I did not know that this stupid tool has such a big watermark.

On the left side you can see the Combat log and on the right side i used an addon called Spellreplay.
This tracks all used spells and shows the damage or if it is a miss or parry (this is also shown in the chat)

I've asked in Discord for support on this topic and even I got no further information there are definitly more people wondering about this issue.

I hope this helps and if you need any further information

https://youtu.be/oQmIsQyNxaQ

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Execute](https://youtu.be/AOE5w4_6YZw)

@Notrox1 
When the fix will be merged, let me know if "Execute" it's okay with this fix I made now.

**Comment by necropola** [comment]
@FrancescoBorzi  Is there a specific reason, why this hasn't been merged yet into CC? We are getting duplicates.

**Comment by Stifler82** [comment]
> @FrancescoBorzi Is there a specific reason, why this hasn't been merged yet into CC? We are getting duplicates.

@necropola 
The fix has been Merged (check carefully), and all these duplicates should be closed, for the simple reason that the issue does not exist, because the problem is not reproducible.

**Comment by necropola** [comment]
> > @FrancescoBorzi Is there a specific reason, why this hasn't been merged yet into CC? We are getting duplicates.
> 
> @necropola
> The fix has been Merged (check carefully), and all these duplicates should be closed, for the simple reason that the issue does not exist, because the problem is not reproducible.
> 
> ![image](https://user-images.githubusercontent.com/1884642/117176525-e6f75c80-adc7-11eb-8820-555ec68f8329.png)

@Stifler82 
Ok, I found the commit in CC, too.

I understand that your PR fixed the original (this) issue and the new incoming issues aren't really duplicates but invalid since the issue no longer exists?

**Comment by Notrox1** [comment]
Sorry but the Issue definitly still exists. The bug has been reported and it happened to me like 100 times while leveling up to 39.
IMO it was gone before the bracket release went live. But i can not confirm.

**Comment by formiclol** [comment]
> The fix has been Merged (check carefully), and all these duplicates should be closed, for the simple reason that the issue does not exist, because the problem is not reproducible.

@Stifler82 I just hit 24 on my warrior yesterday and noticed this issue immediately.  I'll attempt to capture this happening on video if I get a chance to play tonight.

**Comment by Stifler82** [comment]
> > The fix has been Merged (check carefully), and all these duplicates should be closed, for the simple reason that the issue does not exist, because the problem is not reproducible.
> 
> @Stifler82 I just hit 24 on my warrior yesterday and noticed this issue immediately. I'll attempt to capture this happening on video if I get a chance to play tonight.

ok I will check soon when I'll get some non-busy time..

**Comment by formiclol** [comment]
@Stifler82 Got a pretty clear instance of this.  Mob gets below 20%, I use Execute with 19 rage.  I spend all rage, the animation plays, and the visual effect shows up on the mob, but nothing happens.  The mob ends up dying to a rend tick.  My bet is that this is a bug with the combat log and the mob perried/dodged or i missed?

https://user-images.githubusercontent.com/84552520/120741237-86803b80-c4a9-11eb-95a3-36328df2573b.mp4

slowed down:

https://user-images.githubusercontent.com/84552520/120741561-19b97100-c4aa-11eb-84b5-e6aae9cf5adc.mp4

**Comment by necropola** [comment]
Please post your combat log.

**Comment by Stifler82** [comment]
> My bet is that this is a bug with the combat log and the mob perried/dodged or i missed?

Probably. I have to check about it, but as I told you before, I'm little bit busy in this days, I promise you that I'll check it ASAP.

**Comment by formiclol** [comment]
>I'm little bit busy in this days, I promise you that I'll check it ASAP.

No worries!  As mentioned previously in this/another ticket, it happens so infrequently that it's not game breaking or anything.

>Please post your combat log.

I'll try to capture again tonight with the combat log visible.  This may have been discussed elsewhere on this topic, but there is no entry in the combat log for Execute when this happens.  It's as if you didn't even use the ability (even though you lose rage), which is why i think it's a combat log issue to begin with.
