### ISSUE TITLE
[The Sun Gate] Gate not destoryable

### ISSUE THREAD

**Issue by OA350** [chromiecraft/chromiecraft#3013]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When all Controllers are there, they gate can be clicked on, but the attack doesn't destroy it.
If you destroy the controllers however (as it should be done), the gate is not clickable anymore. Logout/Login doesn't help.
Details see video

### Expected Blizzlike Behaviour

Destroy controllers, swim up to the gate, destroy it by clicking on it

### Source

https://user-images.githubusercontent.com/76611816/153257037-68e26e73-3d85-4ed4-ae76-65ccc439bea2.mp4

### Steps to reproduce the problem

1. Get the quest
2. Try to finish it like in video

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ZhengPeiRu21** [comment]
This was fixed in a recent PR: https://github.com/azerothcore/azerothcore-wotlk/pull/8593

**Comment by OA350** [comment]
It seems as it wasnt fully fixed since I had this issue yesterday. So maybe the bugfix itself is not 100% correct and fails over time? I've had issues on other servers were quests seemed to work, but if the server was running for a time without restart, they bugged out. Only to work again after restart.
Just a plain guess

**Comment by Dimness** [comment]
Confirmed. This bug happened to me exactly as described, another player there at the time was having a similar issue but was eventually able to complete the quest by interacting with the portal with all the controllers still active. I was unable to do the same for no reason either of us could tell.
