### ISSUE TITLE
Error when in WSG

### ISSUE THREAD

**Issue by Chakrah** [chromiecraft/chromiecraft#3604]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

hit with an error code when in WSG.  first 2 times it happened i didnt take screen shots or anything but what i remember is:
- first error occured when horde side and my own race (troll) thats all i remember about this 
- second time i was alliance side as the broken race.  all i remember
- third time was alliance again, had just died and was hit with error when ported to the graveyard
![image](https://user-images.githubusercontent.com/107265526/173209798-60046445-910e-49d7-9473-0365d7352d14.png)

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

error has only occured in WSG.  no new addons have been added since servers last update.
other guildies have had the same error in WSG also since server update, seems to be client side since they also have no changes made to their addons etc

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by armistress** [comment]
This is the third time I'm experiencing this bug, first time after applying a 4g ram patch, that was suggested in a cc support thread I had earlier about this same issue.

![image](https://user-images.githubusercontent.com/107339493/173217489-3c400a1b-eb31-46f0-8171-af26c72da1ed.png)

I was in WSG; on alliance side, looking like a draenei I am (not using the codes to change looks). I was casually trying to get back towards my own base, when the game crashed. On previous occasions I was at the tunnel entrance on both occasions, if that should matter.

Looks like only part of both sides crashed this time, can't say how it's been for previous times.

![image](https://user-images.githubusercontent.com/107339493/173217588-69075cd5-055a-4985-becf-b35f722e1baa.png)

It's CTA weekend and got a position to defend, these deserters are not coming in a good time.

**Comment by benjymansy123** [comment]
Worth pointing out, this issue was also brought up on [Warmane](https://forum.warmane.com/showthread.php?t=445361) a couple months back

**Comment by benjymansy123** [comment]
Could anyone provide the actual crash log file generated from the crash?

**Comment by 55Honey** [comment]
Fixed: https://github.com/azerothcore/mod-cfbg/pull/106

**Comment by armistress** [comment]
This crash is not resolved, still happening. This time in Arathi basin.
[2022-06-15 21.02.19 Crash.txt](https://github.com/chromiecraft/chromiecraft/files/8912014/2022-06-15.21.02.19.Crash.txt)
.
