### ISSUE TITLE
[PTR][AQ20] Moam problems

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#3761]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Mob: https://wowgaming.altervista.org/aowow/?npc=15340
1. Boss aggro radius is small.
2. Moam starts with full mana thus casts Arcane Explosion from the start.
3. Boss doesn't cast Drain Mana on target.
4. Phase 2 - Turn to Stone -  Mana Fiends do not cast Arcane Explosion and Counterspell.
5. Phase 2 - Turn to Stone - boss continues to get mana endlessly (reset mana from max to zero and continues again).
6. Phase 2 - Turn to Stone boss do not return to normal state after all 3  Mana Fiends are killed or 90 secs are passed.

### Expected Blizzlike Behaviour

1. Boss aggro radius should be bigger.
2. Moam should start with zero mana.
3. Boss should cast drain mana on target.
4. Mana Fiends should cast Arcane Explosion and Counterspell.
5. Boss should not continue drain mana and reset it from mana from max to zero and gain it again w/o any mechanics.
6. He should return to normal condition if  after all 3  Mana Fiends are killed or 90 secs are passed.

### Source

1. https://www.youtube.com/watch?v=vZ78PHwMMpE - 37:30
2. https://classic.wowhead.com/guides/moam-ruins-of-ahnqiraj-strategy - At the beginning of the fight, Moam will start the fight at 0 Mana.
3. https://classic.wowhead.com/guides/moam-ruins-of-ahnqiraj-strategy - Moam will constantly cast Drain Mana on 6 random mana users in the raid, draining 500 Mana from them and gaining 1000 Mana for every user drained.
4. https://classic.wowhead.com/guides/moam-ruins-of-ahnqiraj-strategy - they do have a dangerous Arcane Explosion cast (with no knock-up) and a 12-second duration Counterspell. 
5. https://classic.wowhead.com/guides/moam-ruins-of-ahnqiraj-strategy - While turned to stone, Moam will stop his mana drains.
6. https://classic.wowhead.com/guides/moam-ruins-of-ahnqiraj-strategy - After either 90 seconds have passed, or all 3 Mana Fiends are dead, Moam will turn back to normal, repeating the beginning of the fight until he is defeated.

### Steps to reproduce the problem

1. Go to AQ20 at PTR.
2. Engage the boss.
3. Observe incorrect behaviour.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR -  AzerothCore rev. 1d6dc750fa37 2022-07-09 21:38:58 +0000 (master branch) (Unix, Debug, Static)

**Comment by temperrr** [comment]
@kerricsson 

Can you recheck this issue on the PTR and see what has been fixed?

**Comment by kerricsson** [comment]
Hello, check was done at PTR version AzerothCore rev. 6ad764c520c2 2022-08-07 01:05:05 -0700 (master branch) (Unix, Debug, Static):

1.  Boss aggro radius should be bigger. - not fixed.
2.  Moam should start with zero mana. - fixed
3.  Boss should cast drain mana on target. - partially fixed, In accordance with https://classic.wowhead.com/guides/moam-ruins-of-ahnqiraj-strategy and https://wowwiki-archive.fandom.com/wiki/Moam he should drains 500 Mana from player and gaining 1000 Mana for every user drained. On PTR he gains 650 Mana from player and gaining 1500 Mana for every user drained:
![изображение](https://user-images.githubusercontent.com/104144379/183306858-1c013719-417c-416d-9c08-29e1792e80e6.png)
4. Mana Fiends should cast Arcane Explosion and Counterspell. - fixed
5. Boss should not continue drain mana and reset it from mana from max to zero and gain it again w/o any mechanics. - This assumption was wrong - https://vanilla.warcraftlogs.com/reports/gXbNHR2KqCjF4mxv#fight=last&type=resources&hostility=1&pins=0%24Separate%24%23244F4B%24resources%241%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%240%24100&spell=100&view=events  - in accordance with Blizzlike behaviour he also should get mana - 500 mana per second- see "Resource charge" at screenshot:

![изображение](https://user-images.githubusercontent.com/104144379/183307542-be411841-55df-4076-b25f-27c5ed35f13a.png)

6. He should return to normal condition if after all 3 Mana Fiends are killed or 90 secs are passed. - fixed

In addition following problems were discovered:
7. He don't have range for evade - you can drag him far away from his spot.
8.  If he casts  Arcane Explosion right at 90 second of fight or will have almost max mana for 2nd phase and grant 500 mana at second phase - he casts Arcane Explosion, turn of stone form and start attack players with his Mana Fiends. Boss should remain in stone form during whole flight.
9. After fall down from Arcane Explosion melee player can not hit boss - he's at evade mode and do not : 
![изображение](https://user-images.githubusercontent.com/104144379/183307882-88f6524a-a3f0-4024-9a7c-be9ed100dcb1.png)

**Comment by temperrr** [comment]
@kerricsson What do you mean with 5?

7. is normal, we tested that on retail
8. is intended
9. is a bigger maps issue that cant be adressed for this boss specifically.

**Comment by Nyeriah** [comment]
Yes, the stone phase ends when he reaches full mana, he explodes and goes back to p1, tested this on retail

**Comment by kerricsson** [comment]
kk, sorry then. We've spent around 30 mins analyzing AQ20 videos and reported this issue. Seems like it's time for me also to level toon at retail to test stuff here.

**Comment by Nyeriah** [comment]
he has a 500 gain aura during stone phase, could it be that he was in stone phase?
