### ISSUE TITLE
[Minor] NPC's options occassionally becomes non-interactive after spending too much time in the dialogue window

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#3997]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

**Staying in the interaction window occasionally makes any option non-interactive (dialogue, quest, vendor, etc), which is widely common across countless NPCs (I reported it long ago, but it still appears #3015)**

Also certain dialogue chains do not close the NPC's window at the last stage which is also present in recorded cases below:
(#4045)
(#4044) 
(#3964)

____
_Edit:_
**_Old video of this issue_**: https://youtu.be/bOG-sDuYhd0?t=10

____

### Expected Blizzlike Behaviour

Certain dialogues should close the NPC interaction window and the dialogue chain should not soft-crash at all

### Source

_Far too generic issue related to far too often skipped feature to find any reliable one_

### Steps to reproduce the problem

1. Just find an NPC with chat bubble and follow the video steps (especially #3015). Self-explanatory I would say.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e0b7c7d0d3b1ea65860439add2c676b3e18f8f8b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ZhengPeiRu21** [comment]
Thank you for the reporting. These issue need to be fixed individually, so it will be most easy for track if we can either list each case of this happen or open issue for each one.

**Comment by Sathrenor** [comment]
@ZhengPeiRu21 Thank You for the feedback, I've branched out those two issues to separate reports and edited this one to focus on the generic NPCs issues.

**Comment by BeefSteaker** [comment]
unable to replicate what i think is the main issue of this post.
could you clarify specifically what the issue is and any particular npc's it happens with

**Comment by Sathrenor** [comment]
@BeefSteaker 
_Clarification_:
Occasionally, if the player spend too much time or after he clicked the white "chat" bubble in NPC window (this panel with text and options how to interact with it. The screen where You have Red-Gold _Goobye_ button), other options like _"show me Your wares"_ or _"I want to make this inn my home"_ won't trigger any interface action untill the window is reopened.
_**Addons are not an issue and to my knowledge I wasn't the only one. I think I also tried with the other client as well**_

_Related NPCs_:
Hard to account, it was like least half of those who had a white "chatting" bubble, with few examples like Franclorn #3964 or the quest NPC at the very end of Uldaman, and I think Darnassus/Stormwind Inkeeper as well.

**Comment by strangeling** [comment]
I think what I am dealing with is related, but please tell me if I should make a new issue.

Deathguard Saltain in Deathknell (Undead starting area) is constantly pacing around. When you open a dialogue window to talk to them, they walk away forcing the window to close.

I believe the first time this happened was when I was about to accept the quest Scavenging Deathknell. I was in the middle of reading the quest text when they walked away, forcing the window closed and automatically accepting the quest (even though I never clicked accept).

Here's a recording of this: 

https://user-images.githubusercontent.com/43366959/197926550-72b89389-5408-464d-9126-82a2b2079157.mp4

Also, here is a YouTube video of WoW Classic where they talk to Deathguard Saltain as well. Notice how they just stand still, seem to have a in-a-dialogue-standing-still-so-I'm-kinda-bored animation and they don't walk away:
https://youtu.be/4r8Aq4qj7OQ?t=2403

Lastly, I also noticed that my quest objective reads differently just before turning it in than the one from the YouTube video (showing 6/6 instead of 'go back to x in x'). But I am not sure that's related.

**Comment by Sathrenor** [comment]
@strangeling I apologise, but I'm afraid it's not related at all to the posted issue.
_For a future reference, [this (0:12)](https://www.youtube.com/watch?v=bOG-sDuYhd0) is what I meant._

And yes, I think it will be better to make a new ticket. Especially given this one will be left on the back of the shelf and may not leave it at all.

**Comment by The-GhostRider** [comment]
Hello, I am familiar with the issue you claim to be a "bug."
Yes, it can possibly be resolved through C++ programming.
However, it is not exactly a true bug but rather an "order of priority" assigned to the dialogue window.

Allow me to provide a clearer explanation of the matter.
The "Quest" option and the "Chat Bubble" option function based on different mechanisms. Here's what happens:
When you "click" on one mechanism, the other mechanism becomes "canceled" and becomes unusable. To reactivate it, you need to close the window and reopen it.

Therefore, I understand why it may appear as a "bug" to you, but it is not strictly speaking a bug. Certainly, if desired, this mechanism interchange can be scripted more effectively.

Furthermore, as demonstrated in my video, it appears that the issue you reported is no longer present, as the "Chat Bubble" no longer appears.

So, for these reasons I close the report.

[![Anteprima](https://user-images.githubusercontent.com/1884642/247287428-0247c409-e2fa-4bbe-a58e-20f288b93e37.png)](https://www.youtube.com/embed/-GIe81q94Ko)

**Comment by The-GhostRider** [comment]
> @strangeling I apologise, but I'm afraid it's not related at all to the posted issue. _For a future reference, [this (0:10)](https://www.youtube.com/watch?v=bOG-sDuYhd0) is what I meant._

This has been fixed here: https://github.com/azerothcore/azerothcore-wotlk/pull/10627

**Comment by heyitsbench** [comment]
@The-GhostRider This issue has not been fixed and is still present. It is not an issue solely with Renn McGill, but instead across basically all NPCs that create a gossip menu from what I've seen. It has been reported on the AC repo as well [here](https://github.com/azerothcore/azerothcore-wotlk/issues/15989) as well as possibly again on the CC repo [here](https://github.com/chromiecraft/chromiecraft/issues/5701). It does not seem to be a very consistent issue, and I can't even reproduce it on my local install at all, but I very much don't believe this issue to have been fixed, especially since this issue was reported long after your mentioned PR was merged.

**Comment by strangeling** [comment]
@The-GhostRider, what you said makes sense and this happens on official blizz servers to this day.

Especially if there is an NPC with a scripted 'walk'. Sometimes, they have the question above their head. So I can start talking to them and repeatedly click on it, but it won't change. Perfect example is the Shadowlands introductory sequence (not the Maw, but right afterwards, in Oribos when you explain how you escaped), one of the first few quests is to 'Talk to the [someone]' to advance the quest. And if you are in a hurry, before the dialogue ends, it won't advance and it won't be able to be advanced until you close and reopen to the exact same dialogue option, which will now just click.

**Comment by strangeling** [comment]
For what it's worth, the white chat bubble dialogue thing (that can be fixed with closing/reopening the window) happens til this very day on official Blizzard servers. I can probably reproduce it since I have recently run certain content multiple times and triggered this kind of thing often. Always fixed by closing/reopening.

In Shadowlands, in Oribos, when you first get there, there's a quest where you have to talk to Kah-Sher to progress. If you hurry and know this kind of thing will happen, you can actually open the window and see the dialogue option. But if you do it too soon, it won't work until you re-open. No matter how many times you click, even though it looks and visually reacts to your click the same way, etc.

**Comment by The-GhostRider** [comment]
> @The-GhostRider This issue has not been fixed and is still present. It is not an issue solely with Renn McGill, but instead across basically all NPCs that create a gossip menu from what I've seen. It has been reported on the AC repo as well [here](https://github.com/azerothcore/azerothcore-wotlk/issues/15989) as well as possibly again on the CC repo [here](https://github.com/chromiecraft/chromiecraft/issues/5701). It does not seem to be a very consistent issue, and I can't even reproduce it on my local install at all, but I very much don't believe this issue to have been fixed, especially since this issue was reported long after your mentioned PR was merged.

![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/8489b6da-11ac-4c70-bc57-1b48c11d64a1)

**Comment by heyitsbench** [comment]
So [this AC issue](https://github.com/azerothcore/azerothcore-wotlk/issues/15989) is working as intended and can be closed?

**Comment by heyitsbench** [comment]
This is a bug. I am triaging it as the aforementioned already opened AC issue. Thank you for the report, @Sathrenor, I apologize it's taken so long to get to this point.
