### ISSUE TITLE
Glyph of Judgement - only deals 1 damage

### ISSUE THREAD

**Issue by HaydayASX** [chromiecraft/chromiecraft#4123]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

After applying Glyph of Judgment on my level 42 Protection Paladin (Hayday - see picture below), the spells Judgement of Wisdom and Judgement of Light dealt only 1 damage to any enemy NPC of any level. Even after removing the glyph from my talents, the spells dealt the same 1 damage (2 if critical) to NPCs. I tried swapping weapons, relogging on my character, deleting the Cache and WTF folders from the WoW folder separately, but none of these solved the bug.
![WoWScrnShot_092422_001339](https://user-images.githubusercontent.com/114262654/192057845-14a49acb-4ae7-408b-b3a3-b2535b8a192e.jpg)

### Expected Blizzlike Behaviour

I believe that the Judgement spells from the Retribution specialization should deal 188% of the character's spell power, so it should scale with the character's stats and level.
![screenshot_judgement_of_wisdom](https://user-images.githubusercontent.com/114262654/192058186-c1b81795-15f2-42bf-a1ef-844c544a637e.png)

### Source

~ I couldn't find any source ~

### Steps to reproduce the problem

1. Apply the Glyph of Judgement on a Paladin character (mine was Human level 42).
2. Target any enemy NPC and use the Judgement of Light or Judgement of Wisdom spell.
3. See if damage is bigger than 2 (critical hit).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/23f432c6b502c55c2e32749cd2b607d3eb752366

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Thank you for the report! Seems some spells were unintentionally nerfed in the last update. We're working on this right now.

**Comment by Gultask** [comment]
Fixed by the latest hotfix. Thanks a lot for the report!

**Comment by HaydayASX** [comment]
Bug still persists after leveling up, changing items, talents etc. (see picture below)
![WoWScrnShot_092822_215307](https://user-images.githubusercontent.com/114262654/192865431-cbe27d40-0d5d-49fc-86fc-e1a2f9302193.jpg)
