### ISSUE TITLE
[AQ40] Ouro's Sand Blast doesn't hit targets

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#4311]
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

[Sand Blast](https://classic.wowhead.com/spell=26102/sand-blast) has no effect on targets in most cases

### Expected Blizzlike Behaviour

Should always have an effect on targets in 180-degree cone in the direction Ouro

### Source

https://www.wowhead.com/classic/guide/ouro-temple-of-ahnqiraj-strategy

### Steps to reproduce the problem

1. Pull Ouro
2. Wait for sand blast cast

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Contrubius** [comment]
I'm not sure it should always have an effect on the targets. Sand Blast is essentially a binary spell, meaning it can be completely resisted or fully hit, I took multiple blows, rarely resisting, but it should not always 100% hit targets. 
![sand blast description](https://user-images.githubusercontent.com/100415626/198263849-eb0c84ca-12ca-4280-861d-9e0f95ca53ae.png)

**Comment by Santaria94** [comment]
> I'm not sure it should always have an effect on the targets. Sand Blast is essentially a binary spell, meaning it can be completely resisted or fully hit, I took multiple blows, rarely resisting, but it should not always 100% hit targets. ![sand blast description](https://user-images.githubusercontent.com/100415626/198263849-eb0c84ca-12ca-4280-861d-9e0f95ca53ae.png)

I was on PTR with Plasmashield. I think here it is necessary to clarify that this was not resistance. It seems that Ouro remembers a certain sector and uses Sand Blast only on that sector, regardless of his current location. We were turning the boss, I was behind him and I was hit by Sand Blast.

**Comment by Cooties-cc** [comment]
Correct on direction of sand blast being bugged. Perhaps this is what the ticket should pertain to. We noticed in our attempts before a kill, that sand blast was never in the direction the boss was facing past the initial pull. It wasn't till I noticed that hunter pets are scripted to always be behind their target, and thus, hunter pets showed that the back of the boss was not always linked to his model direction. It was a big key to figuring out why the raid was still getting sand blasts, but also a big bug. I thought I had seen a post up about this after we had done it, but maybe was worded wrong.

**Comment by Gultask** [comment]
Fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/13578

**Comment by balleny** [comment]
Issue is still persisting (the fix never actually worked).
Ouro is Sandblasting into a direction, not on the highest threat target

**Comment by balleny** [comment]
@Gultask issue still persists and should be flagged accordingly :)

Sandblast direction is pre-determined and not based on the position of the person highest in threat.

**Comment by Gultask** [comment]
This seems to be an issue where no one can actually reliably reproduce it.
Like with the Twin Emperors not pausing after the Teleport. They do it correctly when testing but not in a raid environment.

**Comment by balleny** [comment]
> This seems to be an issue where no one can actually reliably reproduce it. Like with the Twin Emperors not pausing after the Teleport. They do it correctly when testing but not in a raid environment.

I can reproduce it 100% on each pull, after each submerge and in enrage - just need a second person. Cooties practically described all the necessary information, just not with reproducible steps:

1) engage boss with a melee (tank)
2) set pet on boss
3) pet will be in the back of the boss, opposite side of the "next" Sandblast
4) tank can move into pet position as sandblast direction is already determined opposite of pet at this point.
5) after sandblast, recall pet and send it in again on the boss (important factor here is, that the pet must not be highest in threat, because then the pet would attack from the front. This could happen when trying to reproduce and the pet overtakes in aggro because the current tank gets hit from sandblast)
6) repeat.

**Comment by Gultask** [comment]
@balleny I can try it out but I'm a bit busy these days for several reasons.
If you're sure of it, you can open a AC issue and I'll add the necessary labels.

**Comment by Nyeriah** [comment]
Sandblast does not target pets. Ouro will not choose pets as a valid target for sand blast.
