### ISSUE TITLE
[Terokkar Forest] Bonechewer Ruins - Marauders and Messengers not patrolling from their spawn point at Ruins to Shadowmoon Valley

### ISSUE THREAD

**Issue by HasieEST** [chromiecraft/chromiecraft#4716]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Title says it all. Visual context below.

![image](https://user-images.githubusercontent.com/25981761/210164066-e51179f2-3fa4-4c2d-a152-ef23db48a610.png)

### Expected Blizzlike Behaviour

They spawn previously visualized spots and proceed to patrol as group of 5 onwards to Terokkar Road and from there up close to Illidari point, where they get ambushed and killed by Wrathwalkers, who despawn shortly after the encounter.

### Source

https://www.wowhead.com/tbc/npc=21245/bonechewer-marauder
Might need a sniff to get a proper visual representation.

### Steps to reproduce the problem

Pretty much arrive at their spawn point and observe. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c05c45c51d3d414ab3bec40e3e4bc2b5c10a977e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
note that the spawning wrathstalker currently has a loot table, which shouldnt be the case
retail: https://www.wowhead.com/wotlk/npc=21249/wrathstalker
AZ/TC: https://db.rising-gods.de/?npc=21249#drops

**Comment by balleny** [comment]
actually just witnessed them running, including the spawn event etc.

**Comment by HasieEST** [comment]
Intriguing,. at the time of writing it was not, prehaps there was a fix that was pushed before hand?

**Comment by Pyromanihack** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/14335

**Comment by Paradigmxd** [comment]
This is actually still not working as intended :D :D -- Let me explain.

The patrol is now happening at the ambush point. However, Stalkers appear and kill the messenger and then run away, leaving either 4 or 1-2 Marauders alive and they sit there whilst stuck in 1 place....

**Comment by Paradigmxd** [comment]
> Fixed by [azerothcore/azerothcore-wotlk#14335](https://github.com/azerothcore/azerothcore-wotlk/pull/14335)

Not working as intended at all

**Comment by Paradigmxd** [comment]
![WoWScrnShot_040123_170224](https://user-images.githubusercontent.com/100602999/229301632-bf667d9a-22ac-4e7b-8d6d-78b179090544.jpg)


See - Messenger dead - Marauders immobilized and untouched :D: D:
