### ISSUE TITLE
[Global, Paladin] Paladin Aura spams combat log while stationary.

### ISSUE THREAD

**Issue by Vyperhand** [chromiecraft/chromiecraft#5517]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

When playing a paladin with any aura active, will occasionally see the combat log start spamming/scrolling "Your 'aura name' has been applied to World Invisible Trigger" then immediately "Your 'aura name' has faded from World Invisible Trigger."

The only thing I have found is this seems to only when you're standing still.  Therefore I have noticed it the most often waiting on a boat dock, or waiting on a zeppelin tower.  It seems to happen slightly more frequently with Retribution Aura than Devotion Aura, but that could just be a problem with my sample size.  As soon as I start to move again, the messages stop.

### Expected Blizzlike Behaviour

These messages should not appear.  Looks like World Invisible Trigger is recorded as an NPC?
https://www.wowhead.com/tbc/npc=12999/world-invisible-trigger

### Source

Don't really have a usable source, but I can say I have never seen this behavior before in any version of WoW back to TBC's initial launch.

### Steps to reproduce the problem

1. Log on to a paladin
2. Enable an aura, Retribution for example
3. For a static point, go to the departure point for the Org-TB zeppelin outside Orgrimmar
4. Wait a few seconds, watching the combat log.
5. If it does not start, move slightly or target and de-target a nearby NPC and then stand still again.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Windows 10 Home 21H2

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
This may have been fixed, I've taken a paladin and stood it next to one of these trigger NPCs with retribution aura on, but nothing weird in the combat log. Could you find a specific spot on the PTR where this happens and throw the `.gps` coordinates here?

**Comment by Vyperhand** [comment]
@heyitsbench  - definitely not fixed.  Just started happening with my wife's paladin inside the Auberdine inn.  37,44
![image](https://github.com/chromiecraft/chromiecraft/assets/131016474/2f0b83e9-ffc2-47b3-b284-bbc99352e961)

**Comment by Rorschach91** [comment]
Unable to Reproduce.
I tried with two different paladins, but nothing happened.

I close this issue. Thank you anyway.
