### ISSUE TITLE
Jumping in water can make you swim to the bottom of the water.

### ISSUE THREAD

**Issue by heyitsbench** [chromiecraft/chromiecraft#6634]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Currently if you spam jump in a water, sometimes your character will forcibly swim to the bottom of the water.

### Expected Blizzlike Behaviour

This should not happen.

### Source

Assumption.

### Steps to reproduce the problem

1. Spam jump in water while moving.
2. Observe.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
are you sure it is only the jumping in? so far i only experienced it after at least diving / submerging
but i have never gotten pulled down when "hopping" into the water only

**Comment by heyitsbench** [comment]
> are you sure it is only the jumping in?

It is very possible it happens in other situations, but I have definitely had issues (particularly in Darrowmere Lake) where just hopping on the surface of the water over and over sends me down.

**Comment by elthehablo** [comment]
Blink also does this sometimes. Looks like the z coordinate cannot always be correctly set on teleportation when in water

**Comment by heyitsbench** [comment]
> Blink also does this sometimes.

That should have been resolved with [this commit](https://github.com/azerothcore/azerothcore-wotlk/commit/0d4adf5a3ee542a90966b48407da9c78975fe059), wonder what broke it again.

**Comment by elthehablo** [comment]
Definitely not fixed. Had this happen a few months back still

**Comment by Plan414** [comment]
Been happening to all raid members in SSC. I have not heard or see it happen to someone in a week so maybe there was a recent fix?

**Comment by CMHWoody** [comment]
Can confirm, Blink sends you to the bottom...fast.  In testing, it seems it happens specifically when on the surface of the water and the destination puts you also in water (blink works normally when blinking from water to land), and when blinking submerged, blink also seems to behave normally. If I was venture to guess it's an issue with abilities like jump or blink where the game calculates a destination on a water surface and loses it's z coordinate, or maybe uses a 0 value and 0 is whatever the "bottom" of the world is.
