### ISSUE TITLE
[TK] Trash - Nether Scryer

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#6748]
### What client do you play on?

Other

### Faction

Both

### Content Phase:

70

### Current Behaviour

Dominate is casted to all raid members making the whole raid run under Mind Control
https://youtu.be/Y8cMTH3vIng?si=IoL94ImI9sLBFo7b&t=6179

### Expected Blizzlike Behaviour

It should be a single target spell

### Source

https://www.wowhead.com/wotlk/spell=37135/domination

### Steps to reproduce the problem

1. .tele eye
2. get to solarian room
3. engage a Netherscryer with more than 1 person, see the whole party get mind controlled

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
they should mind control 5 targets
https://youtu.be/FEYAX7l5H6A?t=4902
https://youtu.be/9yNphoQW890?t=8064

Star Scryers should MC 1 person only

**Comment by Cooties-cc** [comment]
My report, https://github.com/chromiecraft/chromiecraft/issues/6646, comments on the workings of the mob. It was flagged as fixed, however something broke or it wasn't fixed correctly. 5 targets is correct.

**Comment by elthehablo** [comment]
Should have been fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/18394

**Comment by heyitsbench** [comment]
> Ideally need someone to go in one of these days to make sure this is still broken

Still broken as of https://github.com/azerothcore/azerothcore-wotlk/commit/016d9806

**Comment by elthehablo** [comment]
odd

**Comment by elthehablo** [comment]
Well damn. The PR did work. Something else is still making it being cast on everyone
