### ISSUE TITLE
[The Eye] Killing Infinity Blade last in p2 doesn't make Kael'thas transition into p3 unless the phase timer is over.

### ISSUE THREAD

**Issue by amed80** [chromiecraft/chromiecraft#6886]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

If you kill [Infinity Blade](https://wowgaming.altervista.org/aowow/?npc=21271) (the dagger) as the last weapon in phase 2 , Kael'thas will not transition into phase 3 unless the whole 2mn for phase 2 is over.

https://github.com/chromiecraft/chromiecraft/assets/8395873/b7623f47-df83-4935-b83b-cf45a8b18e7c

### Expected Blizzlike Behaviour

Phase 3 should start instantly if all weapons are killed.

### Source

https://www.warcrafttavern.com/tbc/guides/kaelthas-sunstrider/
![image](https://github.com/chromiecraft/chromiecraft/assets/8395873/4cb67cbd-fa34-4e5f-84db-8fec49335e9b)

### Steps to reproduce the problem

1. .tele eye
2. Engage with Kael'thas
3. Kill his advisors and transition to p2
4. Make sure that Infinity Blade is the last weapon alive then kill it.

### Extra Notes

I tried multiple attempts with killing other weapons last but only could reproduce it with the dagger.
This is similar to #6713 but now it's only the dagger.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3bcdc4d23e9b9fa951bf02a74a77a4313078e823

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
Should be fixed with https://github.com/azerothcore/azerothcore-wotlk/commit/8faaa7731917ee5a313911614ef9c5abaed8a23b (looking at commit in hash)

**Comment by amed80** [comment]
https://github.com/chromiecraft/chromiecraft/assets/8395873/78420dfd-6aa0-433f-b1d3-a995445cf486

I don't know but this behavior still exist with the dagger only.

**Comment by amed80** [comment]
Ok , i think i got this completely wrong (same as #6713 ) about Phase 2 transitioning to Phase 3, some guides are saying that you either need to kill all weapon or wait for the timer to run out , but watching couple of videos from wotlk prepatch and speedruns in later expansions, this is NOT the case , Kael'thas should always wait for the timer in P2 to run out even if you kill all weapons , he only skip timer from P3 to P4 (killing advisors)

[Video 1](https://youtu.be/z23ellU5BRo) This is a speedrun from Legion i think , you can see at 4:06 he killed all weapons and had to wait for almost 1m25sec after killing the last weapon before the boss started his RP.
[Video 2](https://www.youtube.com/watch?v=z23ellU5BRo) Another Speedrun is Legion also , at 6:56 he kills the last weapon and wait until 8:16 is when KT start his RP for P3.
[Video 3](https://youtu.be/0_buJV0r_rY) A Video of how to farm Ashes of Al'ar during MoP , at 3:58 you can see Asmongold waiting 1m20sec after killing the weapons before P3 starts.
[Video 4](https://youtu.be/UdpS6qoc8t0) Wotlk classic pre patch , at 45:11 they killed all weapons and waited almost another minute before KT started his RP.
[Video 5](https://youtu.be/eO9YLOIUc9w) Wotlk classic pre patch , at 2:49 the killed all weapons and waited until 3:44 for KT to start his RP for P3.

so currently only the dagger is actually following the correct? behavior compared to other weapons ...

Also the timer for P2 is ~1:45 and not 2mn (this need more verification)

Should i close this report and make a new one with all of those as sources ? or this comment here is enough ?
